@startuml dynamic_simulation

start

partition INITIALIZE {

    :Load parameters; <<load>>

    :Define transfer functions; <<procedure>>

    :Find poles; <<task>>

    :Find Nyquist frequency; <<task>>

    :Define simulation frequency; <<task>>

    :Initialize variables; <<load>>

    :Initialize delay buffer; <<load>>

    :Initialize storage vectors; <<load>>

}

partition LOOP {

    repeat

        partition CONTROL {

            :Compute control error; <<task>>

            if (thet_e > delta?) then (yes)

                :up = 1; <<task>>

            elseif (thet_e < -delta?) then (yes)

                :up = -1; <<task>>

            else (no)

                :up = 0; <<task>>

            endif

            :Apply delay buffer; <<procedure>>

        }

        :Compute actuator dynamics; <<continuous>>

        :Compute satellite dynamics; <<continuous>>

        :Compute sensor dynamics; <<continuous>>

        :Integration; <<procedure>>


        :Store simulation data; <<save>>


    repeat while (k < N)

}

:Generate plots; <<output>>

stop

@enduml